title: Bahadoor Kattubadi # your name (or website title) here
logo: "/profile.png.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Aspiring DevOps Engineer
  <br><br>
  <a href="mailto:bahadoor1796@rguktrkv.ac.in">bahadoor1796@rguktrkv.ac.in</a>
  <br>
  <a href="linkedin.com/in/bahadoor-kattubadi-344854118">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/bahadoor009/">Github</a> 
theme: jekyll-theme-minimal
